#!/bin/bash

# optional parameter: delete files
# This deletes files made in the intermediate steps
# Helps not clog up the directory
# Note this does not delete the original data!

# Check required paramter
reqparams=2
if [ $# -lt $reqparams ];then
	echo "Usage requires 2 sac files"
	exit
fi
sfiles=($1 $2)
#sfile=$1
mode=$3

if [[ $mode == *clean* || $mode == *CLEAN* ]];then
	echo "Clean has been set"
	echo "All files other than the original and the psa txt file will be deleted upon completion"
	CLEAR=1
fi

first="yes"
# This is the difference between pair and single. Complete all processing for both until PSA.
for sfile in ${sfiles[@]}
do

# Check if the file is a sac file 
if [[ $sfile != *.Sac && $sfile != *.SAC && $sfile != *.sac ]]; then
	echo "Usage requires a sac file with extension .Sac , .SAC or .sac"
	exit
fi

# Get the event parameters from the sac file using saclhdr
YEAR=`saclhdr -NZYEAR $sfile`
JDAY=`saclhdr -NZJDAY $sfile`
MAG=`saclhdr -MAG $sfile`
DIST=`saclhdr -DIST $sfile`
NPTS=`saclhdr -NPTS $sfile`
OT=`saclhdr -O $sfile`
AZ=`saclhdr -CMPAZ $sfile`
DELTA=`saclhdr -DELTA $sfile`
DEPMAX=`saclhdr -DEPMAX $sfile`
DEPMIN=`saclhdr -DEPMIN $sfile`
# ----- Can I separate this from the data requests?? ---
# Remove the mean of the data
# Perform instrument response correctiongs - Done by IDOEVT (No rewrite)
# CHECK to make sure the amplitude values are between 1E-12 and 1 m/s/s
MINAMP=1e-12
MAXAMP=0.1

# Check to see if the max amplitude fits in the expected range
# Sometimes an error occurs where the min value is greater than the max
# This indicated a bad trace and it also thrown out.
# CompGT returns a 1 if the first value is greater than the second
c1=`CompGT $DEPMIN $DEPMAX`
c2=`CompGT $DEPMAX $MAXAMP`
c3=`CompGT $MINAMP $DEPMAX`

if [[ $c1 == 1 || $c2 == 1 || $c3 == 1 ]]; then
	if [[ $CLEAR == 1 ]]; then
		rm ${sfile}.*
	fi
	echo "Amplitude values are not within the expected range."
	echo "The trace should not be used."
	echo "freq=-999"
	echo "Rfreq=-999"
	exit
fi 
# Window and taper the data
	# Taper is done with gsac taper
# Zero Pad the Data
# Get the number of seconds to add with zeros
ADD=`GetZeros $NPTS $DELTA`

# Zero pad the data
	# Use gsac CUT command.
	# Allows for n seconds to be added
	# Make sure there are the correct number of pts in the record
gsac << EOF
r $sfile
taper
w append .taper

cuterr fillz
cut E $ADD
r $sfile.taper
w append .pad
quit
EOF

cfile=$sfile.taper.pad
sac2ascii_c $cfile
LENGTH=`wc -l $cfile.ascii`
# LENGTH Should be the same as N2 and is a power of 2

# Calculate the intersection ratios of noise and signal
	# Save the freq for intersection and ratio of 3
# LowCornFreq has a variety of checks internally including:
	# Check if the event time is within the signal
	# Check if the distance is positive
	# A variety of checks to see if the frequency content is valuable
inter=`LowCornFreq $DIST $OT $LENGTH $MAG $DELTA`
freq=`echo "$inter" | cut -f1`
Rfreq=`echo "$inter" | cut -f2`

echo "freq=$freq"
echo "Rfreq=$Rfreq"

if [ $Rfreq == -1 ];then
	if [[ $CLEAR == 1 ]]; then
		rm ${sfile}.*
	fi
	echo "Checks failed while computing signal to noise"
	echo "The event may not occur during the signal or"
	echo "The signal to noise ratio may not be sufficient"
	echo "Check the temp.txt file."
	exit;
fi

# Use the freq of ratio 3 to perform a highpass filter.
	# Use pass 2
# Remove the zero pad
	# Can again be done with the CUT command.
# Integrate the record twice to get the displacement
gsac << EOF
r $cfile
hp n 2 pass 2 c $Rfreq
w append .filt

cut E -$ADD
r $cfile.filt
w $sfile.filt

int
int
w $sfile.disp
quit
EOF

# Fit a poly to the displacement
sac2ascii_c $sfile.disp
dfile=$sfile.disp.ascii
sac2ascii_c $sfile.filt
afile=$sfile.filt.ascii

ndfile=$sfile.disp.new
nafile=$sfile.acc.end

# Remove the second derivative from the acceleration
octave << EOF
format long;
d = load('$dfile');
a = load('$afile');
pts=size(a,1);

tim = d(:,1);
pos = d(:,2);
P = polyfit(tim,pos,logical([1 1 1 1 1 0 0]));

acoeff = fliplr(P(1:5)); 
acoeff = acoeff .* [2 , 6 , 12 , 20 , 30]
dcoeff = fliplr(P);

apoly = zeros(pts,1) + acoeff(1);
dpoly = zeros(pts,1) + dcoeff(1); 
for i=1:4
	apoly = acoeff(i+1)*tim.^(i) + apoly;
end
for i=1:6
	dpoly = dcoeff(i+1)*tim.^(i) + dpoly;
end

tim = a(:,1);
acc = a(:,2);
accNEW = acc - apoly;
dNEW = pos - dpoly;

awrit=fopen('$nafile','w');
dwrit=fopen('$ndfile','w');
for i=1:pts
	fprintf(awrit,'%f %.10e\n',tim(i)',accNEW(i)');
	fprintf(dwrit,'%f %.10e\n',tim(i)',dNEW(i)');
end
quit
EOF

# Get the parameters necessary for the GmRotD50 calculations.
if [ $first = "yes" ];then
	first="no"
	nafile1=$nafile
	NPTS1=$NPTS
	az1=$AZ
fi  

done
set -x
# Chck if the displacement is acceptable.
# Perform response spectra calculations for a set of periods
# These are the periods that will be examined
periods=( "0.1" "0.2" "0.3" "0.5" "1.0" "2.0" "3.0" "5.0" "10.0")

DAT="$DIST\n"
for p in "${periods[@]}" 
do
DAT="${DAT}$p\t"
done
DAT="$DAT\n"

for p in "${periods[@]}"
do

psa=`GmRotD50 $NPTS $nafile $NPTS1 $nafile1 $DELTA $AZ $az1 $p`
DAT="${DAT}$psa\t"
done

if [[ $CLEAR == 1 ]]; then
	for sfile in ${sfiles[@]}
	do
	rm ${sfile}.*
	done
fi

# Ugly perl chomp gets ride of the last new line
echo -e "$DAT" | perl -pe 'chomp if eof' >> $sfile.psa

